//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""MouseClick"",
            ""id"": ""6b2a451b-24cc-4c05-92dd-99c887f6ece6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""a4a955ba-6111-45d1-ae99-4e936551634e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b9a37f35-b225-48d3-8130-1cde1153936d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GridMovement"",
            ""id"": ""00395115-aebc-4003-8fed-7d5563bf395c"",
            ""actions"": [
                {
                    ""name"": ""North"",
                    ""type"": ""Button"",
                    ""id"": ""80b53f27-e8e1-4140-80d8-3cc76ccf907f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""West"",
                    ""type"": ""Button"",
                    ""id"": ""3b3d0762-1d03-437d-b7b2-bf5fe8b3be17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""South"",
                    ""type"": ""Button"",
                    ""id"": ""30f3453b-1b2e-4508-82f2-566e84fdc993"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""East"",
                    ""type"": ""Button"",
                    ""id"": ""adadf644-29d8-4724-b421-83163595defb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""37e3dff7-9cab-4be6-b34b-9e6285222e35"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56c48b03-8375-4820-92fb-264858dbaeed"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcfcfaba-465f-4fdb-b5aa-805a55949120"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""917020a0-0ba4-468a-8bdc-5d04d8203389"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MouseClick
        m_MouseClick = asset.FindActionMap("MouseClick", throwIfNotFound: true);
        m_MouseClick_Move = m_MouseClick.FindAction("Move", throwIfNotFound: true);
        // GridMovement
        m_GridMovement = asset.FindActionMap("GridMovement", throwIfNotFound: true);
        m_GridMovement_North = m_GridMovement.FindAction("North", throwIfNotFound: true);
        m_GridMovement_West = m_GridMovement.FindAction("West", throwIfNotFound: true);
        m_GridMovement_South = m_GridMovement.FindAction("South", throwIfNotFound: true);
        m_GridMovement_East = m_GridMovement.FindAction("East", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MouseClick
    private readonly InputActionMap m_MouseClick;
    private IMouseClickActions m_MouseClickActionsCallbackInterface;
    private readonly InputAction m_MouseClick_Move;
    public struct MouseClickActions
    {
        private @PlayerControls m_Wrapper;
        public MouseClickActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MouseClick_Move;
        public InputActionMap Get() { return m_Wrapper.m_MouseClick; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseClickActions set) { return set.Get(); }
        public void SetCallbacks(IMouseClickActions instance)
        {
            if (m_Wrapper.m_MouseClickActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MouseClickActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MouseClickActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MouseClickActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_MouseClickActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public MouseClickActions @MouseClick => new MouseClickActions(this);

    // GridMovement
    private readonly InputActionMap m_GridMovement;
    private IGridMovementActions m_GridMovementActionsCallbackInterface;
    private readonly InputAction m_GridMovement_North;
    private readonly InputAction m_GridMovement_West;
    private readonly InputAction m_GridMovement_South;
    private readonly InputAction m_GridMovement_East;
    public struct GridMovementActions
    {
        private @PlayerControls m_Wrapper;
        public GridMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @North => m_Wrapper.m_GridMovement_North;
        public InputAction @West => m_Wrapper.m_GridMovement_West;
        public InputAction @South => m_Wrapper.m_GridMovement_South;
        public InputAction @East => m_Wrapper.m_GridMovement_East;
        public InputActionMap Get() { return m_Wrapper.m_GridMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GridMovementActions set) { return set.Get(); }
        public void SetCallbacks(IGridMovementActions instance)
        {
            if (m_Wrapper.m_GridMovementActionsCallbackInterface != null)
            {
                @North.started -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnNorth;
                @North.performed -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnNorth;
                @North.canceled -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnNorth;
                @West.started -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnWest;
                @West.performed -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnWest;
                @West.canceled -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnWest;
                @South.started -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnSouth;
                @South.performed -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnSouth;
                @South.canceled -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnSouth;
                @East.started -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnEast;
                @East.performed -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnEast;
                @East.canceled -= m_Wrapper.m_GridMovementActionsCallbackInterface.OnEast;
            }
            m_Wrapper.m_GridMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @North.started += instance.OnNorth;
                @North.performed += instance.OnNorth;
                @North.canceled += instance.OnNorth;
                @West.started += instance.OnWest;
                @West.performed += instance.OnWest;
                @West.canceled += instance.OnWest;
                @South.started += instance.OnSouth;
                @South.performed += instance.OnSouth;
                @South.canceled += instance.OnSouth;
                @East.started += instance.OnEast;
                @East.performed += instance.OnEast;
                @East.canceled += instance.OnEast;
            }
        }
    }
    public GridMovementActions @GridMovement => new GridMovementActions(this);
    public interface IMouseClickActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IGridMovementActions
    {
        void OnNorth(InputAction.CallbackContext context);
        void OnWest(InputAction.CallbackContext context);
        void OnSouth(InputAction.CallbackContext context);
        void OnEast(InputAction.CallbackContext context);
    }
}
